### PR TITLE
git commit/push only on changes

### PR DESCRIPTION
**Pull request by martinhpedersen**
Abort early if no changes to push.

Will this work? 🤔

### CODE REVIEW

**Comment by xylo04** [comment]
Let's wait and see overnight. In other places where I've had CI doing commits, I've been able to rely on the fact that git won't create empty commits.

If this does prove necessary, this looks ok to me.

**Comment by martinhpedersen** [comment]
Sounds good 🙂

**Comment by martinhpedersen** [comment]
The "builds" are failing with the error "nothing to commit". Merging this 🤞

**Comment by xylo04** [comment]
Glad you had this ready!

**Pull request merged**
